from .detection import detect_message_level_label_gaps
from .documents import (
    AttachmentDisposition,
    AttachmentSnapshot,
    DocumentCandidate,
    DocumentClass,
    DocumentEvidence,
    DocumentSignificance,
    assess_document_significance,
)
from .inference import confidence_band, infer_label_from_thread
from .model import (
    ConfidenceBand,
    ContextStatus,
    InferenceEvidence,
    LabelClass,
    LabelEvidence,
    LabelGapCandidate,
    LabelInference,
    MessageSnapshot,
    ThreadSnapshot,
)
from .obsolescence import (
    ObsolescenceAssessment,
    ObsolescenceClass,
    ObsolescenceConflict,
    ObsolescenceContext,
    ObsolescenceEvidence,
    ObsolescenceRecommendation,
    assess_message_obsolescence,
)
from .operational import (
    OperationalConflict,
    OperationalEvidence,
    OperationalExecutionStatus,
    OperationalLabelSpec,
    OperationalLayerConfig,
    OperationalMutationAuthorization,
    OperationalRecommendation,
    OperationalState,
    OperationalStateAssessment,
    OperationalStateProposal,
    assess_operational_state,
)
from .protection import (
    DestructiveProtectionGate,
    DestructiveProtectionGateResult,
    ProtectedDomain,
    ProtectedDomainAssessment,
    ProtectedDomainHint,
    ProtectionCoverage,
    ProtectionEvidence,
    ProtectionStatus,
    evaluate_destructive_protection_gate,
    infer_protected_domains,
)
from .reporting import (
    AuthorizationReason,
    DryRunCandidateReport,
    DryRunReport,
    ExecutionStatus,
    MutationAuthorization,
    MutationClass,
    PlannedAction,
    RepairRecommendation,
    SafetyGateResult,
    build_dry_run_report,
    render_dry_run_json,
    render_dry_run_text,
)

from .audit import (
    AUDIT_SCHEMA_VERSION,
    AuditMessageRecord,
    AuditSummary,
    AuditWarning,
    AuditWarningCode,
    MailboxAuditReport,
    ProviderLimitation,
    TaxonomyLabelSummary,
    build_mailbox_audit,
    render_mailbox_audit_json,
    render_mailbox_audit_text,
)


from .change_log import (
    CHANGE_LOG_SCHEMA_VERSION,
    ChangeAuditRecord,
    ChangeEvidence,
    DryRunProposalReference,
    MailboxStateSnapshot,
    MutationAction,
    MutationExecutionMode,
    MutationInitiator,
    MutationResultStatus,
    ProviderResultMetadata,
    RollbackMetadata,
    SafetyGateDecision,
    SafetyGateRecord,
    append_change_record_jsonl,
    correlation_id_for_dry_run,
    render_change_log_jsonl,
    render_change_record_json,
    render_change_record_text,
)



from .gmail_auth import (
    GMAIL_READONLY_SCOPE,
    GMAIL_MODIFY_SCOPE,
    GmailAccountSafeId,
    GmailAuthError,
    GmailAuthErrorCode,
    GmailAuthManager,
    GmailAuthPaths,
    GmailAuthSession,
    GmailAuthorizationMode,
    GmailOAuthBackend,
    GoogleInstalledAppOAuthBackend,
    scopes_for_mode,
)



from .gmail_provider import (
    GMAIL_MESSAGE_STRUCTURE_FIELDS,
    GMAIL_MIME_MAX_DEPTH,
    GmailReadAdapter,
    GmailReadRetryPolicy,
    GmailReadTransport,
    GoogleGmailReadTransport,
)

from .ingestion import (
    IngestedMessageAttachments,
    MailboxIngestionResult,
    ProviderAwareLabelClassifier,
    ingest_provider_mailbox,
)

from .provider import (
    ProviderDescriptor,
    ProviderErrorCode,
    ProviderIdentity,
    ProviderLabelKind,
    ProviderLabelSnapshot,
    ProviderMessageSnapshot,
    ProviderMessageState,
    ProviderOperationError,
    ProviderPage,
    ProviderReadAdapter,
    ProviderReadCapabilities,
    ProviderReadCapability,
    ProviderThreadRef,
    ProviderWriteCapabilities,
    ProviderWriteCapability,
)


__all__ = [
    "AttachmentDisposition",
    "AttachmentSnapshot",
    "AuthorizationReason",
    "ConfidenceBand",
    "ContextStatus",
    "DestructiveProtectionGate",
    "DestructiveProtectionGateResult",
    "DocumentCandidate",
    "DocumentClass",
    "DocumentEvidence",
    "DocumentSignificance",
    "DryRunCandidateReport",
    "DryRunReport",
    "ExecutionStatus",
    "InferenceEvidence",
    "LabelClass",
    "LabelEvidence",
    "LabelGapCandidate",
    "LabelInference",
    "MessageSnapshot",
    "MutationAuthorization",
    "MutationClass",
    "ObsolescenceAssessment",
    "ObsolescenceClass",
    "ObsolescenceConflict",
    "ObsolescenceContext",
    "ObsolescenceEvidence",
    "ObsolescenceRecommendation",
    "OperationalConflict",
    "OperationalEvidence",
    "OperationalExecutionStatus",
    "OperationalLabelSpec",
    "OperationalLayerConfig",
    "OperationalMutationAuthorization",
    "OperationalRecommendation",
    "OperationalState",
    "OperationalStateAssessment",
    "OperationalStateProposal",
    "PlannedAction",
    "ProtectedDomain",
    "ProtectedDomainAssessment",
    "ProtectedDomainHint",
    "ProtectionCoverage",
    "ProtectionEvidence",
    "ProtectionStatus",
    "RepairRecommendation",
    "SafetyGateResult",
    "ThreadSnapshot",
    "assess_document_significance",
    "assess_message_obsolescence",
    "assess_operational_state",
    "build_dry_run_report",
    "confidence_band",
    "detect_message_level_label_gaps",
    "evaluate_destructive_protection_gate",
    "infer_label_from_thread",
    "infer_protected_domains",
    "render_dry_run_json",
    "render_dry_run_text",
    "AUDIT_SCHEMA_VERSION",
    "AuditMessageRecord",
    "AuditSummary",
    "AuditWarning",
    "AuditWarningCode",
    "MailboxAuditReport",
    "ProviderLimitation",
    "TaxonomyLabelSummary",
    "build_mailbox_audit",
    "render_mailbox_audit_json",
    "render_mailbox_audit_text",
    "CHANGE_LOG_SCHEMA_VERSION",
    "ChangeAuditRecord",
    "ChangeEvidence",
    "DryRunProposalReference",
    "MailboxStateSnapshot",
    "MutationAction",
    "MutationExecutionMode",
    "MutationInitiator",
    "MutationResultStatus",
    "ProviderResultMetadata",
    "RollbackMetadata",
    "SafetyGateDecision",
    "SafetyGateRecord",
    "append_change_record_jsonl",
    "correlation_id_for_dry_run",
    "render_change_log_jsonl",
    "render_change_record_json",
    "render_change_record_text",
    "GMAIL_READONLY_SCOPE",
    "GMAIL_MODIFY_SCOPE",
    "GmailAccountSafeId",
    "GmailAuthError",
    "GmailAuthErrorCode",
    "GmailAuthManager",
    "GmailAuthPaths",
    "GmailAuthSession",
    "GmailAuthorizationMode",
    "GmailOAuthBackend",
    "GoogleInstalledAppOAuthBackend",
    "scopes_for_mode",
    "GMAIL_MESSAGE_STRUCTURE_FIELDS",
    "GMAIL_MIME_MAX_DEPTH",
    "GmailReadAdapter",
    "GmailReadRetryPolicy",
    "GmailReadTransport",
    "GoogleGmailReadTransport",
    "IngestedMessageAttachments",
    "MailboxIngestionResult",
    "ProviderAwareLabelClassifier",
    "ingest_provider_mailbox",
    "ProviderDescriptor",
    "ProviderErrorCode",
    "ProviderIdentity",
    "ProviderLabelKind",
    "ProviderLabelSnapshot",
    "ProviderMessageSnapshot",
    "ProviderMessageState",
    "ProviderOperationError",
    "ProviderPage",
    "ProviderReadAdapter",
    "ProviderReadCapabilities",
    "ProviderReadCapability",
    "ProviderThreadRef",
    "ProviderWriteCapabilities",
    "ProviderWriteCapability",

]
